##-- Homework --##

import math

print(math.sin(30))
print(math.cos(30))
print(math.tan(30))
print(math.sin(45))
print(math.cos(45))
print(math.tan(45))
print(math.sin(60))
print(math.cos(60))
print(math.tan(60))
print(math.sin(90))
print(math.cos(90))
print(math.tan(90))
print(math.sin(180))
print(math.cos(180))
print(math.tan(180))
print(math.sin(270))
print(math.cos(270))
print(math.tan(270))
print(math.sin(360))
print(math.cos(360))
print(math.tan(360))
print(math.sin(0))
print(math.cos(0))
print(math.tan(0))